# Docker Compose for BankingLLM system

services:
  # Ollama service for LLM
  ollama:
    image: ollama/ollama:latest
    container_name: banking-llm-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # Gradio Web UI service
  banking-llm-web:
    build:
      context: .
      target: web
    container_name: banking-llm-web
    ports:
      - "8505:8505"
    volumes:
      - ./data/exports:/app/data/exports:rw  # Export files directory
      # Database is pre-built in image - no volume mounting needed
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - LLM_MODEL=qwen2.5:7b
      - LOG_LEVEL=INFO
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local