# Development overrides for BankingLLM system
version: '3.8'

services:
  # Development Ollama with more verbose logging
  ollama:
    environment:
      - OLLAMA_DEBUG=1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  # Development API with hot reload and debugging
  banking-llm-api:
    volumes:
      - ./src:/app/src:ro  # Read-only mount for hot reload
      - ./data/exports:/app/data/exports:rw  # Only exports directory
      # Database is pre-built in image - no need to mount
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - LLM_MODEL=llama3.1:8b
      - LOG_LEVEL=DEBUG  # Verbose logging for development
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port
    command: ["python", "-m", "uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "src"]

  # Development Web with hot reload
  banking-llm-web:
    volumes:
      - ./src:/app/src:ro  # Read-only mount for hot reload
      - ./data/exports:/app/data/exports:rw  # Only exports directory
      # Database is pre-built in image - no need to mount
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - LLM_MODEL=llama3.1:8b
      - LOG_LEVEL=DEBUG
      - STREAMLIT_SERVER_RUNONDAVE=true
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "src/web.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.fileWatcherType=poll"]

  # Development database viewer (optional)
  adminer:
    image: adminer
    container_name: banking-llm-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=sqlite
      - ADMINER_DESIGN=pepa-linha